# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["nodejs-18_x", "npm"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node dist/index.js"

[variables]
NODE_ENV = "production"
PORT = "3001"
